language: java
jdk: oraclejdk11

os: linux

env:
  - REPO_USER_NAME=qa REPO_USER_PASSWORD=qa123ws

before_cache:
- rm -f  $HOME/.gradle/caches/modules-2/modules-2.lock
- rm -fr $HOME/.gradle/caches/*/plugin-resolution/

# cache the build tool's caches
cache:
  directories:
    - $HOME/.m2
    - $HOME/.gradle

before_install: ignore

jobs:
  include:
    - stage: Assembly
      install: skip
      before_script: echo "<STAGE 'Assembly 'islaunchingup...>"
      script: gradle assemble
      after_success: echo "<STAGE 'Assembly 'has been executed successfully>"
      after_failure: echo "<STAGE 'Assembly 'has been failed>"

    - stage: UnitTest
      name: "[allure.integration] Module Tests"
      script:
        - cd allure.integration
        - gradle test

    - name: "[allure.testng.bridge] Module Tests"
    - script:
        - cd allure.testng.bridge
        - gradle test

    - name: "[check] Module Tests"
    - script:
        - cd check
        - gradle test

    - name: "[core.api] Module Tests"
    - script:
        - cd core.api
        - gradle test

    - name: "[data.base.api] Module Tests"
    - script:
        - cd data.base.api
        - gradle test

    - name: "[http.api] Module Tests"
    - script:
        - cd http.api
        - gradle test

    - name: "[selenium] Module Tests"
    - script:
        - cd selenium
        - gradle test

    - name: "[testng.integration] Module Tests"
    - script:
        - cd testng.integration
        - gradle test

    - stage: deploy
      install: skip
      script: skip
