language: java
jdk: oraclejdk11

os: linux

branches:
  only:
    - master

before_cache:
  - rm -f  $HOME/.gradle/caches/modules-2/modules-2.lock
  - rm -fr $HOME/.gradle/caches/*/plugin-resolution/

# cache the build tool's caches
cache:
  directories:
    - $HOME/.m2
    - $HOME/.gradle

before_install: ignore

jobs:
  include:
    # Build/Assembly stage
    - stage: Assembly
      install: skip
      before_script: echo "<STAGE 'Assembly 'is launching up...>"
      script: gradle assemble
      after_success: echo "<STAGE 'Assembly 'has been executed successfully>"
      after_failure: echo "<STAGE 'Assembly 'has been failed>"

    # Test stage
    - stage: Test
      name: "[allure.integration] Module Tests"
      script:
        - cd allure.integration
        - gradle test

    - stage: Test
      name: "[allure.testng.bridge] Module Tests"
      script:
        - cd allure.testng.bridge
        - gradle test

    - stage: Test
      name: "[check] Module Tests"
      script:
        - cd check
        - gradle test

    - stage: Test
      name: "[core.api] Module Tests"
      script:
        - cd core.api
        - gradle test

    - stage: Test
      name: "[data.base.api] Module Tests"
      script:
        - cd data.base.api
        - gradle test

    - stage: Test
      name: "[http.api] Module Tests"
      script:
        - cd http.api
        - gradle test

    - stage: Test
      name: "[selenium] Module Tests"
      script:
        - cd selenium
        - gradle test

    - stage: Test
      name: "[testng.integration] Module Tests"
      script:
        - cd testng.integration
        - gradle test

    # in case of a need for continuous deployment (Docker as an example), you have to set up this stage
    # Follow-up step is to make 'Heroku' account to do so
    # Deployment stage
    - stage: Deploy
      install: skip
      script: skip
      provider: skip
